---
# source
source:
  - "/appspace/src"
destination: "/appspace/dst"
# arrage_method options: copy, move
arrange_method: "copy"
# on_duplicate: "drop", 'skip", only effected on arrange_method == "move"
on_duplicate: "drop"
respect_mtime: "no"
log_dir: "/appspace/logs"
chown: "no"
chown_uid: 1
chown_gid: 1
file_mod: 0440
dir_mod: 0551