---
version: 1
disable_existing_loggers: True
incremental: False
formatters:
  detailed:
    class: logging.Formatter
    format: "|%(asctime)s|%(name)s|%(filename)s|%(lineno)d|%(levelname)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: xxx.log
loggers:
  app:
    handlers:
    - console
    - file
    level: INFO
  parser:
    handlers:
    - console
    - file
    level: INFO
  file_process:
    handlers:
    - console
    - file
    level: INFO
  mover:
    handlers:
    - console
    - file
    level: INFO
    propagate: False
