---
# source
source:
  - "/appspace/src"
destination: "/appspace/dst"
doubts: "/appspace/dbt"
log_dir: "/appspace/logs"

# arrage_method options: COPY, MOVE
arrange_mode: "COPY"
# on_duplicate: "SKIP', 'DROP', 'MOVE', only effected on arrange_mode == "MOVE"
duplicate_action: "DROP"
duplicate_dest_dir: "/appspace/dup"

respect_mtime: "no"

acl: "no"
acl_uid: 1
acl_gid: 1
acl_filemod: 0440
acl_dirmod: 0551